export const Nav2Constants = [
  {
    id: 1,
    title: "DashBoard",
    level: 1,
    isExpandedd2: "collapsed",
  },
  {
    id: 2,
    title: "Achat",
    level: 1,
    isExpandedd2: "collapsed",
  },
  {
    id: 2,
    title: "Commandes",
    level: 2,
    isExpandedd2: "disabled",
  },
  {
    id: 2,
    title: "Transactions",
    level: 2,
    isExpandedd2: "disabled",
  },
  {
    id: 3,
    title: "Boutique",
    level: 1,
    isExpandedd2: "collapsed",
  },
  // {
  //   id: 3,
  //   title: "Astuce & Conseil",
  //   level: 2,
  //   isExpandedd2: false,
  // },
  {
    id: 3,
    title: "Banniere",
    level: 2,
    isExpandedd2: "disabled",
  },
  // {
  //   id: 3,
  //   title: "Disposition",
  //   level: 2,
  //   isExpandedd2: false,
  // },
  // {
  //   id: 3,
  //   title: "Type Astuce & Conseil",
  //   level: 2,
  //   isExpandedd2: false,
  // },
  {
    id: 4,
    title: "Catalogue",
    level: 1,
    isExpandedd2: "collapsed",
  },
  {
    id: 4,
    title: "Gestion promotion",
    level: 2,
    isExpandedd2: "disabled",
  },
  {
    id: 4,
    title: "Gestion produits",
    level: 2,
    isExpandedd2: "disabled",
  },

  {
    id: 4,
    title: "Gestion catégorie produits",
    level: 2,
    isExpandedd2: "disabled",
  },
  // {
  //   id: 4,
  //   title: "Gestion packs",
  //   level: 2,
  //   isExpandedd2: "disabled",
  // },
  // {
  //   id: 4,
  //   title: "Gestion type packs",
  //   level: 2,
  //   isExpandedd2: "disabled",
  // },
  {
    id: 5,
    title: "Ressource humaine",
    level: 1,
    isExpandedd2: "collapsed",
  },
  {
    id: 5,
    title: "Gestion administrateurs",
    level: 2,
    isExpandedd2: "disabled",
  },
  {
    id: 5,
    title: "Gestion clients",
    level: 2,
    isExpandedd2: "disabled",
  },
  {
    id: 5,
    title: "Gestion role et permissions",
    level: 2,
    isExpandedd2: "disabled",
  },
  {
    id: 6,
    title: "Parametre",
    level: 1,
    isExpandedd2: "collapsed",
  },
  {
    id: 6,
    title: "Gestion Zone",
    level: 2,
    isExpandedd2: "disabled",
  },
  {
    id: 6,
    title: "Gestion prix livraison",
    level: 2,
    isExpandedd2: "disabled",
  },
];
